Repository leroy-merlin-br/garden, pull requests merged in 2019-10, with the labels that each got.

#382 fix(readme): remove codeship as we are not using it anymore
  README.md
Labels: chore, should review

#408 docs(readme): remove bower mentions
  README.md
Labels: Hacktoberfest, docs

#409 chore(houndci): remove config from project
  .hound.yml
Labels: Hacktoberfest, chore

#410 chore(bower): remove bower config
  bower.json
Labels: Hacktoberfest, chore
